version: '3.2'
volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  elastic:
    driver: bridge

services:
  backend:
    image: document-search-system-backend
    networks:
      - elastic
    ports:
      - 8080:8080
    environment:
      - APPLICATION_ELASTIC_SERVER_HOST=elastic
      - APPLICATION_FILESYSTEM_ROOT=/files
    volumes:
      - data02:/files
  elastic:
    build: ./elastic
    container_name: elastic
    environment:
      - node.name=elastic
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./plugins:/plugins
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

